// providerCatalog is the static registry of OpenAI-compatible providers.
// Each entry ships a base URL, default model, and capability map.
package providers

var providerCatalog = []ProviderSpec{
	{Name: "nvidia", BaseURL: "https://integrate.api.nvidia.com/v1", DefaultModel: "meta/llama-3.1-70b-instruct",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": true, "tool_calling": true, "reasoning": true}, MaxContext: 128000},
	{Name: "openai", BaseURL: "https://api.openai.com/v1", DefaultModel: "gpt-4o",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": true, "tool_calling": true}, MaxContext: 128000},
	{Name: "groq", BaseURL: "https://api.groq.com/openai/v1", DefaultModel: "llama-3.3-70b-versatile",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "ollama", BaseURL: "https://ollama.com/v1", DefaultModel: "llama3.1",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": true, "tool_calling": true}, MaxContext: 128000},
	{Name: "openrouter", BaseURL: "https://openrouter.ai/api/v1", DefaultModel: "anthropic/claude-sonnet-4",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": false, "tool_calling": true}, MaxContext: 200000,
		ExtraHeaders: map[string]string{"HTTP-Referer": "https://github.com/ElJoker63/my-gateway", "X-Title": "My Gateway AI"}},
	{Name: "google", BaseURL: "https://generativelanguage.googleapis.com/v1beta/openai", DefaultModel: "gemini-2.5-flash",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": true, "tool_calling": true}, MaxContext: 1000000},
	{Name: "cloudflare", BaseURL: "", DefaultModel: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": true, "tool_calling": false}, MaxContext: 128000},
	{Name: "github_models", BaseURL: "https://models.github.ai/inference", DefaultModel: "openai/gpt-4o",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": true, "tool_calling": true}, MaxContext: 128000},
	{Name: "sambanova", BaseURL: "https://api.sambanova.ai/v1", DefaultModel: "Meta-Llama-3.3-70B-Instruct",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "chutes", BaseURL: "https://llm.chutes.ai/v1", DefaultModel: "deepseek-ai/DeepSeek-V3.2",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "fireworks", BaseURL: "https://api.fireworks.ai/inference/v1", DefaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": true, "tool_calling": true}, MaxContext: 128000},
	{Name: "hyperbolic", BaseURL: "https://api.hyperbolic.xyz/v1", DefaultModel: "meta-llama/Llama-3.3-70B-Instruct",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "opencode", BaseURL: "https://opencode.ai/zen/v1", DefaultModel: "grok-code-fast-1",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": false, "tool_calling": true, "reasoning": true}, MaxContext: 128000},
	{Name: "opencode_go", BaseURL: "https://opencode.ai/zen/go/v1", DefaultModel: "grok-code-fast-1",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true, "reasoning": true}, MaxContext: 256000},
	{Name: "deepseek", BaseURL: "https://api.deepseek.com/v1", DefaultModel: "deepseek-chat",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "siliconflow", BaseURL: "https://api.siliconflow.cn/v1", DefaultModel: "Qwen/Qwen3-235B-A22B",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": true, "tool_calling": true}, MaxContext: 128000},
	{Name: "modelscope", BaseURL: "https://api-inference.modelscope.cn/v1", DefaultModel: "Qwen/Qwen3-235B-A22B-Instruct-2507",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "zhipu", BaseURL: "https://open.bigmodel.cn/api/paas/v4", DefaultModel: "glm-4.5-flash",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "moonshot", BaseURL: "https://api.moonshot.ai/v1", DefaultModel: "kimi-k2-0905-preview",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 200000},
	{Name: "minimax", BaseURL: "https://api.minimax.io/v1", DefaultModel: "MiniMax-M2",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "dashscope", BaseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1", DefaultModel: "qwen-plus",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": true, "tool_calling": true}, MaxContext: 128000},
	{Name: "hunyuan", BaseURL: "https://api.hunyuan.cloud.tencent.com/v1", DefaultModel: "hunyuan-turbos-latest",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 32000},
	{Name: "qianfan", BaseURL: "https://qianfan.baidubce.com/v2", DefaultModel: "ernie-4.0-8k-latest",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": true, "tool_calling": true}, MaxContext: 8192},
	{Name: "sensenova", BaseURL: "https://api.sensenova.cn/compatible-mode/v1", DefaultModel: "SenseChat-5",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 32000},
	{Name: "stepfun", BaseURL: "https://api.stepfun.com/v1", DefaultModel: "step-3",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "lingyiwanwu", BaseURL: "https://api.lingyiwanwu.com/v1", DefaultModel: "yi-lightning",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 32000},
	{Name: "volcengine", BaseURL: "https://ark.cn-beijing.volces.com/api/v3", DefaultModel: "doubao-1.5-pro-32k-250115",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
	{Name: "kilocode", BaseURL: "https://api.kilo.ai/api/openrouter/v1", DefaultModel: "anthropic/claude-sonnet-4",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": true, "embeddings": false, "tool_calling": true}, MaxContext: 1000000},
	{Name: "nous_research", BaseURL: "https://inference-api.nousresearch.com/v1", DefaultModel: "hermes-3-llama-3.1-70b",
		Capabilities: map[string]bool{"chat": true, "streaming": true, "vision": false, "embeddings": false, "tool_calling": true}, MaxContext: 128000},
}
